pipeline {
    agent any

    environment {
        EC2_IP = "13.60.17.138"
    }

    stages {

        stage('Clone Code') {
            steps {
                git 'https://github.com/DILIPPRAJAPATI1/devops-projects.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t project10 ./project10'
            }
        }

        stage('Deploy to EC2') {
            steps {
                sh """
                ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IP '
                    docker stop project10-container || true &&
                    docker rm project10-container || true &&
                    docker run -d --name project10-container -p 3000:3000 project10
                '
                """
            }
        }
    }
}
