pipeline {
    agent any

    stages {

        stage("Clone") {
            steps {
                checkout scm
            }
        }

        stage("Build Docker Image") {
            steps {
                sh "docker stop devops-app || true"
                sh "docker rm devops-app || true"
                sh "docker build -t devops-project1:ci -f project-1-docker/Dockerfile project-1-docker"
            }
        }

        stage("Deploy") {
            steps {
                sh "docker run -d -p 8080:80 --name devops-app devops-project1:ci"
            }
        }
    }
}

