pipeline {
    agent any

    environment {
        IMAGE_NAME = "dilip122390/project8-webapp"
    }

    stages {
        stage("Checkout Code") {
            steps {
                checkout scm
            }
        }

        stage("Build Docker Image") {
            steps {
                sh "docker build -t $IMAGE_NAME:latest app"
            }
        }

        stage("Push to Docker Hub") {
            steps {
                sh "docker push $IMAGE_NAME:latest"
            }
        }

        stage("Deploy to Kubernetes") {
            steps {
                sh "kubectl apply -f k8s/deployment.yaml"
                sh "kubectl apply -f k8s/service.yaml"
            }
        }
    }
}
